version: '3.8'

services:
  scrapy:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - PYTHONPATH=/app:/app/jobs_project:/app/infra
    volumes:
      - .:/app
    working_dir: /app/jobs_project
    command: [ "scrapy", "crawl", "json_spider" ]

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongo_data:
