services:
  scrapy:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app/jobs_project
    command: ["tail", "-f", "/dev/null"]
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - REDIS_URL=redis://redis:6379

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
